[theme]
primaryColor = "#13AA52"        # MongoDB Green
backgroundColor = "#FFFFFF"     # White background
secondaryBackgroundColor = "#F5F7F8"  # Light grey panel background
textColor = "#0A0A0A"
font = "sans serif"
